language: c
dist: focal
compiler:
  - clang
  - gcc

addons:
  apt:
    update: true

before_install:
  - sudo apt-get -y install libmpich-dev libxml2-dev mpich
  - test -n $CC && unset CC

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
