language: c
dist: focal
compiler:
  - clang
  - gcc

addons:
  apt:
    update: true
    packages:
      - libmpich-dev
      - libxml2-dev
      - mpich

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - mpirun ./sboxgates -b ../sboxes/identity.txt -vv -a 10694 -i 3
  - mpirun ./sboxgates -b ../sboxes/linear.txt -vv -a 10694 -i 3
  - mpirun ./sboxgates -b ../sboxes/des_s1.txt -vv -a 10694 -i 3
  - mpirun ./sboxgates -b ../sboxes/crypto1_fa.txt -vv -a 10694 -i 3
  - mpirun ./sboxgates -b ../sboxes/crypto1_fb.txt -vv -a 10694 -i 3
  - mpirun ./sboxgates -b ../sboxes/crypto1_fc.txt -vv -a 10694 -i 3
  - mpirun ./sboxgates -b ../sboxes/identity.txt -vv -i 3
  - mpirun ./sboxgates -b ../sboxes/linear.txt -vv -i 3
  - mpirun ./sboxgates -b ../sboxes/des_s1.txt -vv -i 3
  - mpirun ./sboxgates -b ../sboxes/crypto1_fa.txt -vv -i 3
  - mpirun ./sboxgates -b ../sboxes/crypto1_fb.txt -vv -i 3
  - mpirun ./sboxgates -b ../sboxes/crypto1_fc.txt -vv -i 3
