language: c
dist: focal
compiler:
  - clang
  - gcc

addons:
  apt:
    update: true
    packages:
      - graphviz
      - libmpich-dev
      - libxml2-dev
      - mpich

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - mpirun -N 4 ./sboxgates -b ../sboxes/des_s1.txt -vv -i 3 -o 0
  - mpirun -N 4 ./sboxgates -b ../sboxes/des_s1.txt -vv -i 3 -g 1*.xml
  - rm *.xml
  - mpirun -N 4 ./sboxgates -b ../sboxes/des_s1.txt -vv -a 10694 -i 3
  - ./sboxgates -d 4*.xml | dot -Tpng > /dev/null
  - ./sboxgates -c 4*.xml > test.c
  - gcc -c -Wall -Wpedantic -Werror test.c
  - rm *.xml *.c
  - mpirun -N 4 ./sboxgates -b ../sboxes/des_s1.txt -vv -a 10694 -l -o 0
  - ./sboxgates -d 1*.xml | dot -Tpng > /dev/null
  - ./sboxgates -c 1*.xml > test.c
  - gcc -c -Wall -Wpedantic -Werror test.c
  - rm *.xml *.c
