language: c
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - cmake
      - libxml2-dev
      - mpich

before_install:
  - test -n $CC && unset CC

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
