language: c
dist: focal
compiler:
  - gcc

addons:
  apt:
    update: true
    packages:
      - graphviz
      - libmpich-dev
      - libxml2-dev
      - mpich
      - nvidia-cuda-toolkit

before_install:
  - pip install --user cpp-coveralls

before_script:
  - mkdir build
  - cd build

script:
  - cmake -DENABLE_COVERAGE=ON ..
  - make
  - ./sboxgates --help
  - '! ./sboxgates'
  - '! ./sboxgates -a -123 ../sboxes/des_s1.txt'
  - '! ./sboxgates -a 65536 ../sboxes/des_s1.txt'
  - '! ./sboxgates -i 0 ../sboxes/des_s1.txt'
  - '! ./sboxgates -i -123 ../sboxes/des_s1.txt'
  - '! ./sboxgates -o -123 ../sboxes/des_s1.txt'
  - '! ./sboxgates -o 8 ../sboxes/des_s1.txt'
  - '! ./sboxgates -p -123 ../sboxes/des_s1.txt'
  - '! ./sboxgates -p 256 ../sboxes/des_s1.txt'
  - '! ./sboxgates -c -d test.xml'
  - '! ./sboxgates -l -s ../sboxes/des_s1.txt'
  - '! ./sboxgates nonexisting.txt'
  - '! ./sboxgates -o 7 ../sboxes/des_s1.txt'
  - mpirun -N 4 ./sboxgates -vv -i 3 -o 0 -s -n ../sboxes/des_s1.txt
  - mpirun -N 4 ./sboxgates -vv -i 3 -s -n ../sboxes/des_s1.txt -g 1*.xml
  - rm *.xml
  - mpirun -N 4 ./sboxgates -vv -a 10694 -i 3 -p 63 ../sboxes/des_s1.txt
  - ./sboxgates -d 4*.xml | dot -Tpng > /dev/null
  - ./sboxgates -c 4*.xml > test.c
  - $CC -c -Wall -Wpedantic -Werror test.c
  - rm *.xml *.c *.o
  - mpirun -N 10 ./sboxgates -vv -a 10694 -l -o 0 ../sboxes/des_s1.txt
  - ./sboxgates -d 1*.xml | dot -Tpng > /dev/null
  - ./sboxgates -c 1*.xml > test.cu
  - nvcc -c test.cu

after_success:
  - cd ..
  - coveralls --gcov-options '\-lp' -E '.*CMake.*'
